Curso/urls.py
# bandas/urls.py

from django.urls import path
from . import views  # importamos views para poder usar as suas funções

app_name = 'curso'
urlpatterns = [

    #core do projeto
    path('', views.index_view, name='cursos'),
    path('curso/<int:curso_id>/', views.curso_view, name="curso"),
    path('area/<int:area_id>/', views.area_cientifica_view, name="area"),
    path('disciplina/<int:disciplina_id>', views.disciplina_view, name="disciplina"),
    path('projeto/<str:projeto_id>', views.projeto_view, name="projeto"),


    #criar elementos
    path('curso/novo', views.novo_curso_view, name="novo_curso"),
    path('area/nova/<int:curso_id>', views.nova_area_view,name="nova_area"),
    path('disciplina/nova/<int:area_id>', views.nova_disciplina_view, name="nova_disciplina"),
    path('projeto/novo/<int:disciplina_id>', views.novo_projeto_view, name="novo_projeto"),
    path('linguagem/nova/<int:projeto_id>', views.nova_linguagem_view, name="nova_linguagem"),
    path('docente/novo/<int:disciplina_id>', views.novo_docente_view, name="novo_docente"),



    #Editar Elementos
    path('curso/edita/<int:curso_id>', views.edita_curso_view,name="edita_curso"),
    path('disciplina/edita/<int:disciplina_id>', views.edita_disciplina_view,name="edita_disciplina"),
    path('projeto/edita/<int:projeto_id>', views.edita_projeto_view,name="edita_projeto"),


    #Apagar elementos
    path('apaga_curso/<int:curso_id>', views.apaga_curso_view, name="apaga_curso"),
    path('apaga_area/<int:area_id>', views.apaga_area_view, name="apaga_area"),
    path('apaga_disciplina/<int:disciplina_id>', views.apaga_disciplina_view, name="apaga_disciplina"),
    path('apaga_projeto/<int:projeto_id>', views.apaga_projeto_view, name="apaga_projeto")


]

autenticacao/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'autenticacao'
urlpatterns = [
    path('registo/', views.registo_view, name="registo"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('', views.user_view, name="user"),

    # recuperação de password
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/custom_password_reset_form.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/custom_password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/custom_password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/custom_password_reset_complete.html'), name='password_reset_complete'),
]

bandasNovas/urls.py
from django.urls import path

from . import views

app_name = 'bandasNovas'

urlpatterns = [

    #Core das bandas
    path('', views.index_view, name="bandas"),
    path('banda/<int:banda_id>/', views.banda_view, name="banda"),
    path('album/<int:album_id>/', views.album_view, name="album"),
    path('musica/<int:musica_id>', views.musica_view, name="musica"),



    #Criar elementos
    path('cria_banda/', views.nova_banda_view, name="cria_banda"),
    path('cria_album/<int:banda_id>', views.novo_album_view, name="cria_album"),
    path('cria_musica/<int:album_id>', views.nova_musica_view, name="cria_musica"),



    #Edita elementos
    path('edita_banda/<int:banda_id>', views.edita_banda_view, name="edita_banda"),
    path('edita_album/<int:album_id>', views.edita_album_view, name="edita_album"),
    path('edita_musica/<int:musica_id>', views.edita_musica_view, name="edita_musica"),



    #Apaga elementos
     path('apaga_banda/<int:banda_id>', views.apaga_banda_view, name="apaga_banda"),
    path('apaga_album/<int:album_id>', views.apaga_album_view, name="apaga_album"),
    path('apaga_musica/<int:musica_id>', views.apaga_musica_view, name="apaga_musica")


]

meteo/urls.py
from django.urls import path
from meteo import views
app_name = 'meteo'

urlpatterns = [
    path('tempo_lisboa/', views.lisboa_view, name='tempo_lisboa'),
    path('cinco_dias/',views.view_cinco_dias, name = 'cinco_dias'),
]

portfolio/urls.py
from django.urls import path
from . import views  # importamos views para poder usar as suas funções

app_name = 'portfolio'
urlpatterns = [

    #core do projeto
    path('', views.landing_view, name='landing'),
    path('about_me', views.me_by_me, name='about_me'),


]

projeto1Pw/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),  # novo path
    path('pwsite/', include('pwsite.urls')),  # novo path
    path('novaapp/', include('novaapp.urls')),  # novo path
    path('bandasNovas/', include('bandasNovas.urls')),  # novo path
    path('curso/', include('Curso.urls')),  # novo path
    path('festivais/', include('festivais.urls')),  # novo path
    path('autenticacao/', include('autenticacao.urls')),
    path('meteo/', include('meteo.urls')),
    path('', include('portfolio.urls')),
    path('artigos/', include('artigos.urls')),

    ]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/views.py
from django.shortcuts import render


def landing_view(request):
    imagem =  'portfolio/Portfolio.JPG'
    video1 = 'portfolio/ Portfolio - Google Chrome 2024-06-10 22-53-11.mp4'
    video2 = 'portfolio/projeto1Pw _ _home_a22207489_projeto1Pw _ Directory Listing _ a22207489 _ PythonAnywhere - Google Chrome 2024-06-10 21-08-37.mp4'

    context = {
        'imagem' : imagem,
        'video1': video1,
        'video2':video2,
        }

    return render(request, "portfolio/landing.html",context)


def me_by_me(request):
    imagem =  'portfolio/Afonso Amaral - Resume (1).pdf'
    context = {
        'imagem' : imagem
        }

    return render(request, "portfolio/about_me.html",context)



# Create your views here.

portfolio/templates/portfolio/about_me.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #24272b; /* Dark Gray */
            margin: 0;
            padding: 0;
            color: #FFFFFF; /* White */
            display: flex;
            flex-direction: column;
            height: 100vh; /* Full viewport height */
            width: 100vw; /* Full viewport width */
            overflow: hidden; /* Prevent scrolling */
        }

        .container {
            display: flex;
            flex-direction: column;
            flex: 1;
            width: 100%; /* Ensure the container takes the full width */
            height: 100%; /* Ensure the container takes the full height */
        }

        .navbar {
            background-color: #24272b; /* Dark Gray */
            color: #FFFFFF; /* White */
            width: 100%;
            padding: 15px; /* Adjusted padding for thinner navbar */
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid #5A5A5A; /* Medium Gray */
            height: 70px; /* Set a fixed height for the navbar */
        }

        .navbar h1 {
            margin: 0;
            font-size: 1.5em; /* Adjusted font size */
            flex: 0 0 auto; /* Ensure the title does not shrink */
        }

        .navbar .nav-buttons {
            display: flex;
            gap: 10px; /* Adjusted spacing between buttons */
            justify-content: flex-end; /* Align buttons to the end */
            margin-right: 20px; /* Add margin to the right to shift buttons left */
        }

        .navbar a, .navbar button {
            color: #FFFFFF; /* White */
            text-decoration: none;
            display: flex;
            align-items: center;
            padding: 8px 12px; /* Adjusted padding for buttons */
            font-size: 0.9em; /* Adjusted font size */
            min-width: 100px; /* Set a minimum width for the buttons */
            justify-content: center; /* Center the text inside the buttons */
            border-radius: 5px;
            transition: background-color 0.3s, color 0.3s;
        }
        .navbar button {
            background-color: #5A5A5A; /* Medium Gray */
            border: none;
            color: #FFFFFF; /* White */
            text-decoration: none;
            display: inline-block;
            cursor: pointer;
            border-radius: 5px;
            min-width: 100px; /* Set a minimum width for the buttons */
            justify-content: center; /* Center the text inside the buttons */
        }

        .navbar a:hover, .navbar button:hover {
            background-color: #3A3F44; /* Slightly lighter gray for hover effect */
        }

        .navbar a .material-icons, .navbar button .material-icons {
            margin-right: 5px; /* Adjusted margin */
        }

        .user-info {
            display: flex;
            align-items: center;
            gap: 5px; /* Closer spacing between icon and username */
        }

        main {
            flex: 1;
            display: flex;
            flex-direction: row;
            width: 100%; /* Ensure the main section takes the full width */
            height: calc(100% - 70px); /* Adjust for navbar height */
        }

        .left-panel {
            flex: 1;
            max-width: 40%; /* Increase the width of the left panel */
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            background-color: #24272b; /* Dark Gray */
            padding: 20px; /* Adjust padding */
            height: 100%; /* Ensure the left panel takes the full height */
            overflow: auto; /* Enable scrolling if content overflows */
        }

        .left-panel iframe {
            width: 100%;
            height: 100%;
            border: none;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }

        .right-panel {
            flex: 1;
            max-width: 60%; /* Adjust the width of the right panel */
            padding: 40px; /* Increased padding for better spacing */
            display: flex;
            flex-direction: column;
            justify-content: flex-start;
            background-color: #2E3135; /* Slightly lighter dark gray */
            height: 100%; /* Ensure the right panel takes the full height */
            overflow: auto; /* Enable scrolling if content overflows */
            position: relative; /* For absolute positioning of the clock */
        }

        .right-panel h2, .right-panel h3, .right-panel h4 {
            margin-top: 0;
            margin-bottom: 20px;
        }

        .right-panel h2 {
            color: #A8DADC; /* Light Blue */
            font-size: 1.8em; /* Adjusted font size */
        }

        .right-panel h3 {
            color: #81A1C1; /* Lighter Blue */
            font-size: 1.4em; /* Adjusted font size */
        }

        .right-panel h4 {
            color: #E5E9F0; /* Light Gray */
            font-size: 1.2em; /* Adjusted font size */
        }

        .right-panel p {
            color: #D8DEE9; /* Light Gray */
            line-height: 1.5; /* Improved line height for readability */
        }

        .right-panel a {
            color: #81A1C1; /* Lighter Blue */
            text-decoration: none;
            margin-top: 20px;
            display: inline-block;
            padding: 10px 20px;
            border: 1px solid #81A1C1;
            border-radius: 5px;
            transition: background-color 0.3s, color 0.3s;
        }

        .right-panel a:hover {
            background-color: #81A1C1;
            color: #24272b;
        }

        .profile-image img {
            width: 100%;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }

        .clock {
            font-size: 24px;
            color: #E5E9F0;
            position: absolute;
            top: 20px; /* Position at the top */
            right: 20px; /* Position at the right */
        }

        .light-mode {
            background-color: #F8F9FA; /* Very Light Gray */
            color: #343A40; /* Dark Gray */
        }

        .light-mode .navbar {
            background-color: #FFFFFF; /* White */
            color: #343A40; /* Dark Gray */
            border-bottom: 1px solid #CED4DA; /* Gray */
        }

        .light-mode .left-panel {
            background-color: #E0E0E0; /* Lighter Gray for light mode */
        }

        .light-mode .right-panel {
            background-color: #FFFFFF; /* White */
        }

        .light-mode .navbar button {
            background-color: #FFFFFF; /* Bright Blue */
            color: #000000; /* Black text */
        }

        .light-mode .user-info {
            color: #007BFF; /* Bright Blue */
        }

        .light-mode .navbar a {
            color: #343A40; /* Dark Gray */
        }

        .light-mode .navbar a .material-icons {
            color: #007BFF; /* Bright Blue */
        }
        .light-mode .navbar button:hover {
            background-color: #F8F9FA; /* Darker Gray */
        }


        .light-mode .navbar a:hover .material-icons {
            color: #0056b3; /* Dark Blue */
        }

        .light-mode .right-panel h2 {
            color: #007BFF; /* Bright Blue */
        }

        .light-mode .right-panel p, .light-mode .right-panel a {
            color: #343A40; /* Dark Gray */
        }
    </style>
    <title>Portfolio</title>
</head>
<body class="dark-mode">
    <div class="container">
        <div class="navbar">
            <h1>Portfolio</h1>
            <div class="nav-buttons">
                <a href="{% url 'portfolio:landing' %}"><i class="material-icons">home</i>Home</a>
                <a href="{% url 'curso:cursos' %}"><i class="material-icons">school</i>Curso</a>
                <a href="{% url 'bandasNovas:bandas' %}"><i class="material-icons">library_music</i>Bandas</a>
                <a href="#"><i class="material-icons">article</i>Artigos</a>
                <a href="{% url 'meteo:tempo_lisboa' %}"><i class="material-icons">wb_sunny</i>Meteorologia</a>
                {% if request.user.is_authenticated %}
                    <div class="user-info">
                        <i class="material-icons">person</i>
                        <p>{{ request.user.username }}</p>
                    </div>
                    <a href="{% url 'autenticacao:logout' %}"><button><i class="material-icons">logout</i>Logout</button></a>
                {% else %}
                    <a href="{% url 'autenticacao:login' %}"><button><i class="material-icons">login</i>Login</button></a>
                {% endif %}
                <button onclick="toggleDarkMode()">Toggle Dark/Light Mode</button>
            </div>
        </div>
        <main>
            <div class="left-panel">
                <iframe src="{% static imagem %}" title="PDF Document"></iframe>
            </div>
            <div class="right-panel">
                <div id="clock" class="clock"></div> <!-- Clock is always visible -->
                <h2>Sobre mim</h2>
                <h3>Do lado esquerdo pode ver o meu resume e fazer o seu download assim como imprimir</h3>
                <h2>Informática de Gestão</h2>
                <h3>Neste momento encontro-me a realizar o curso de Informática de Gestão na Lusófona e estou no segundo semestre do segundo ano</h3>

                <h2>Ensino Secundário</h2>
                <h3>Escola Secundária Professor José Augusto Lucas</h3>
                <h4>Ensino secundário terminado com média de 15,5 onde aprendi e fortaleci o meu conhecimento na área das matemáticas e informática.</h4>

                <h2>Experiência Profissional</h2>
                <h3>Neste momento também me encotro a dar explicações e apoios de todas as disciplinas do 1º ao 9º a alunos num centro de estudos</h3>

            </div>
        </main>
    </div>

    <script>
        function toggleDarkMode() {
            document.body.classList.toggle('dark-mode');
            document.body.classList.toggle('light-mode');
        }

        function updateClock() {
            const clockDiv = document.getElementById('clock');
            const now = new Date();
            clockDiv.innerHTML = now.toLocaleTimeString();
            setTimeout(updateClock, 1000);
        }

        // Start the clock when the page loads
        document.addEventListener('DOMContentLoaded', (event) => {
            updateClock();
        });
    </script>
</body>
</html>

portfolio/templates/portfolio/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #24272b; /* Dark Gray */
            margin: 0;
            padding: 0;
            color: #FFFFFF; /* White */
            display: flex;
            flex-direction: column;
            height: 100vh; /* Full viewport height */
            width: 100vw; /* Full viewport width */
            overflow: hidden; /* Prevent scrolling */
        }

        .container {
            display: flex;
            flex-direction: column;
            flex: 1;
            width: 100%; /* Ensure the container takes the full width */
            height: 100%; /* Ensure the container takes the full height */
        }

        .navbar {
            background-color: #24272b; /* Dark Gray */
            color: #FFFFFF; /* White */
            width: 100%;
            padding: 15px; /* Adjusted padding for thinner navbar */
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid #5A5A5A; /* Medium Gray */
            height: 60px; /* Set a fixed height for the navbar */
        }

        .navbar h1 {
            margin: 0;
            font-size: 2em; /* Adjusted font size */
            flex: 0 0 auto; /* Ensure the title does not shrink */
        }

        .navbar .nav-buttons {
            display: flex;
            gap: 10px; /* Adjusted spacing between buttons */
            justify-content: flex-end; /* Align buttons to the end */
            margin-right: 20px; /* Add margin to the right to shift buttons left */
        }

        .navbar a, .navbar button {
            color: #FFFFFF; /* White */
            text-decoration: none;
            display: flex;
            align-items: center;
            padding: 6px 6px; /* Reduced padding for thinner buttons */
            font-size: 0.9em; /* Reduced font size */
            min-width: 100px; /* Set a minimum width for the buttons */
            justify-content: center; /* Center the text inside the buttons */
        }

        .navbar a .material-icons {
            margin-right: 5px; /* Adjusted margin */
        }

        .navbar a:hover .material-icons {
            color: #A8DADC; /* Light Blue */
        }

        .navbar button {
            background-color: #5A5A5A; /* Medium Gray */
            border: none;
            color: #FFFFFF; /* White */
            text-decoration: none;
            display: inline-block;
            cursor: pointer;
            border-radius: 5px;
            min-width: 100px; /* Set a minimum width for the buttons */
            justify-content: center; /* Center the text inside the buttons */
        }

        .navbar button:hover {
            background-color: #2E2E2E; /* Darker Gray */
        }

        .user-info {
            display: flex;
            align-items: center;
            gap: 5px; /* Closer spacing between icon and username */
        }

        main {
            flex: 1;
            display: flex;
            flex-direction: row;
            width: 100%; /* Ensure the main section takes the full width */
            height: calc(100% - 70px); /* Adjust for navbar height */
        }

        .left-panel {
            flex: 1;
            max-width: 40%; /* Increase the width of the left panel */
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            background-color: #24272b; /* Dark Gray */
            padding: 20px; /* Adjust padding */
            height: 100%; /* Ensure the left panel takes the full height */
        }

        .right-panel {
            flex: 1;
            max-width: 60%; /* Adjust the width of the right panel */
            padding: 20px; /* Adjust padding */
            display: flex;
            flex-direction: column;
            justify-content: center;
            background-color: #D6DCE5; /* Slightly lighter dark gray */
            height: 100%; /* Ensure the right panel takes the full height */
            position: relative; /* For absolute positioning of the clock */
        }

        .clock {
            font-size: 24px;
            position: absolute;
            top: 20px;
            right: 20px;
            color: #1E3A8A; /* Navy Blue */
        }

        .right-panel h2 {
            color: #1E3A8A; /* Navy Blue */
            margin: 0;
            font-size: 1.5em; /* Adjust font size */
        }

        .right-panel p {
            color: #FFFFFF; /* Navy Blue */
            margin-top: 10px;
        }

        .right-panel a {
            color: #1E3A8A; /* Navy Blue */
            text-decoration: none;
            margin-top: 20px;
            display: inline-block;
        }

        .profile-image img {
            width: 100%;
            border-radius: 5px;
        }

        .technologies {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            margin-top: 20px;
        }

        .technology {
            background-color: #1E3A8A; /* Navy Blue */
            color: #FFFFFF; /* White */
            padding: 10px;
            border-radius: 5px;
            flex: 1 1 calc(33% - 40px); /* Adjust width and margin for three columns */
            box-sizing: border-box;
            text-align: center;
        }

        .light-mode {
            background-color: #F8F9FA; /* Very Light Gray */
            color: #343A40; /* Dark Gray */
        }

        .light-mode .navbar {
            background-color: #FFFFFF; /* White */
            color: #343A40; /* Dark Gray */
            border-bottom: 1px solid #CED4DA; /* Gray */
        }

        .light-mode .left-panel {
            background-color: #404040; /* Lighter Gray for light mode */
        }

        .light-mode .right-panel {
            background-color: #FFFFFF; /* White */
        }

        .light-mode .navbar button {
            background-color: #FFFFFF; /* White */
            color: #000000; /* Black */
        }

        .light-mode .user-info {
            color: #000000; /* Black */
        }

        .light-mode .navbar button:hover {
            background-color: #F8F9FA; /* Lighter Gray */
        }

        .light-mode .navbar a {
            color: #343A40; /* Dark Gray */
        }

        .light-mode .navbar a .material-icons {
            color: #000000; /* Black */
        }

        .light-mode .navbar a:hover .material-icons {
            color: #0056b3; /* Dark Blue */
        }

        .light-mode .right-panel h2 {
            color: #007BFF; /* Bright Blue */
        }

        .light-mode .right-panel p, .light-mode .right-panel a {
            color: #000000; /* Black */
        }

        .light-mode .technology {
            background-color: #007BFF; /* Bright Blue */
            color: #FFFFFF; /* White */
        }
    </style>
    <title>Portfolio</title>
</head>
<body class="dark-mode">
    <div class="container">
        <div class="navbar">
            <h1>Portfolio</h1>
            <div class="nav-buttons">
                <a href="{% url 'portfolio:landing' %}"><i class="material-icons">home</i>Home</a>
                <a href="{% url 'curso:cursos' %}"><i class="material-icons">school</i>Curso</a>
                <a href="{% url 'bandasNovas:bandas' %}"><i class="material-icons">library_music</i>Bandas</a>
                <a href="#"><i class="material-icons">article</i>Artigos</a>
                <a href="{% url 'meteo:tempo_lisboa' %}"><i class="material-icons">wb_sunny</i>Meteorologia</a>
                {% if request.user.is_authenticated %}
                    <div class="user-info">
                        <i class="material-icons">person</i>
                        <p>{{ request.user.username }}</p>
                    </div>
                    <a href="{% url 'autenticacao:logout' %}"><button><i class="material-icons">logout</i>Logout</button></a>
                {% else %}
                    <a href="{% url 'autenticacao:login' %}"><button><i class="material-icons">login</i>Login</button></a>
                {% endif %}
                <button onclick="toggleDarkMode()">Toggle Dark/Light Mode</button>
            </div>
        </div>
        <main>
            <div class="left-panel">
                <div class="profile-image">
                    <img src="{% static imagem %}" alt="Imagem do perfil">
                </div>
            </div>
            <div class="right-panel">
                <div id="clock" class="clock"></div> <!-- Clock is always visible -->
                <h2>Os meus trabalhos nas suas mãos</h2>
                <p>Tudo sobre mim e os meus trabalhos e projetos</p>
                <a href="{% url 'portfolio:about_me' %}"><button>Sobre mim</button></a>
                
                <h2>Tecnologias usadas neste projeto</h2>

                <div class="technologies">
                    <div class="technology">
                        <h3>HTML</h3>
                        <p>HTML (Hypertext Markup Language) é a linguagem padrão para criar páginas web. Utilizado para estruturar o conteúdo, incluindo textos, imagens, links e outros elementos multimídia.</p>
                    </div>
                    <div class="technology">
                        <h3>CSS</h3>
                        <p>CSS (Cascading Style Sheets) é usado para descrever a apresentação de um documento escrito em HTML ou XML. Utilizado para dar estilo ao layout, cores, fontes e outros aspectos visuais do site.</p>
                    </div>
                    <div class="technology">
                        <h3>JavaScript</h3>
                        <p>JavaScript é uma linguagem de programação que permite implementar funcionalidades complexas em páginas web, como atualizações de conteúdo dinâmico, animações, controlo de multimídia e muito mais.</p>
                    </div>
                    <div class="technology">
                        <h3>Python</h3>
                        <p>Python é uma linguagem de programação de alto nível usada tanto no backend quanto no desenvolvimento web. É conhecido pela sua simplicidade e eficiência, sendo ideal para desenvolvimento de aplicações.</p>
                    </div>
                    <div class="technology">
                        <h3>SQL</h3>
                        <p>SQL (Structured Query Language) é uma linguagem padrão para gestão e manipulação de dadoS. Utilizado para executar tarefas como consultas, inserções, atualizações e exclusões de dados.</p>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script>
        function toggleDarkMode() {
            document.body.classList.toggle('dark-mode');
            document.body.classList.toggle('light-mode');
        }

        function updateClock() {
            const clockDiv = document.getElementById('clock');
            const now = new Date();
            clockDiv.innerHTML = now.toLocaleTimeString();
            setTimeout(updateClock, 1000);
        }

        // Start the clock when the page loads
        document.addEventListener('DOMContentLoaded', (event) => {
            updateClock();
        });
    </script>
</body>
</html>