Curso/urls.py
# bandas/urls.py

from django.urls import path
from . import views  # importamos views para poder usar as suas funções

app_name = 'curso'
urlpatterns = [

    #core do projeto
    path('', views.index_view, name='cursos'),
    path('curso/<int:curso_id>/', views.curso_view, name="curso"),
    path('area/<int:area_id>/', views.area_cientifica_view, name="area"),
    path('disciplina/<int:disciplina_id>', views.disciplina_view, name="disciplina"),
    path('projeto/<str:projeto_id>', views.projeto_view, name="projeto"),


    #criar elementos
    path('curso/novo', views.novo_curso_view, name="novo_curso"),
    path('area/nova/<int:curso_id>', views.nova_area_view,name="nova_area"),
    path('disciplina/nova/<int:area_id>', views.nova_disciplina_view, name="nova_disciplina"),
    path('projeto/novo/<int:disciplina_id>', views.novo_projeto_view, name="novo_projeto"),
    path('linguagem/nova/<int:projeto_id>', views.nova_linguagem_view, name="nova_linguagem"),
    path('docente/novo/<int:disciplina_id>', views.novo_docente_view, name="novo_docente"),



    #Editar Elementos
    path('curso/edita/<int:curso_id>', views.edita_curso_view,name="edita_curso"),
    path('disciplina/edita/<int:disciplina_id>', views.edita_disciplina_view,name="edita_disciplina"),
    path('projeto/edita/<int:projeto_id>', views.edita_projeto_view,name="edita_projeto"),


    #Apagar elementos
    path('apaga_curso/<int:curso_id>', views.apaga_curso_view, name="apaga_curso"),
    path('apaga_area/<int:area_id>', views.apaga_area_view, name="apaga_area"),
    path('apaga_disciplina/<int:disciplina_id>', views.apaga_disciplina_view, name="apaga_disciplina"),
    path('apaga_projeto/<int:projeto_id>', views.apaga_projeto_view, name="apaga_projeto")


]

autenticacao/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'autenticacao'
urlpatterns = [
    path('registo/', views.registo_view, name="registo"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('', views.user_view, name="user"),

    # recuperação de password
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/custom_password_reset_form.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/custom_password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/custom_password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/custom_password_reset_complete.html'), name='password_reset_complete'),
]

bandasNovas/urls.py
from django.urls import path

from . import views

app_name = 'bandasNovas'

urlpatterns = [

    #Core das bandas
    path('', views.index_view, name="bandas"),
    path('banda/<int:banda_id>/', views.banda_view, name="banda"),
    path('album/<int:album_id>/', views.album_view, name="album"),
    path('musica/<int:musica_id>', views.musica_view, name="musica"),



    #Criar elementos
    path('cria_banda/', views.nova_banda_view, name="cria_banda"),
    path('cria_album/<int:banda_id>', views.novo_album_view, name="cria_album"),
    path('cria_musica/<int:album_id>', views.nova_musica_view, name="cria_musica"),



    #Edita elementos
    path('edita_banda/<int:banda_id>', views.edita_banda_view, name="edita_banda"),
    path('edita_album/<int:album_id>', views.edita_album_view, name="edita_album"),
    path('edita_musica/<int:musica_id>', views.edita_musica_view, name="edita_musica"),



    #Apaga elementos
     path('apaga_banda/<int:banda_id>', views.apaga_banda_view, name="apaga_banda"),
    path('apaga_album/<int:album_id>', views.apaga_album_view, name="apaga_album"),
    path('apaga_musica/<int:musica_id>', views.apaga_musica_view, name="apaga_musica")


]

meteo/urls.py
from django.urls import path
from meteo import views
app_name = 'meteo'

urlpatterns = [
    path('tempo_lisboa/', views.lisboa_view, name='tempo_lisboa'),
    path('cinco_dias/',views.view_cinco_dias, name = 'cinco_dias'),
]

portfolio/urls.py
from django.urls import path
from . import views  # importamos views para poder usar as suas funções

app_name = 'portfolio'
urlpatterns = [

    #core do projeto
    path('', views.landing_view, name='landing'),
    path('about_me', views.me_by_me, name='about_me'),


]

projeto1Pw/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),  # novo path
    path('pwsite/', include('pwsite.urls')),  # novo path
    path('novaapp/', include('novaapp.urls')),  # novo path
    path('bandasNovas/', include('bandasNovas.urls')),  # novo path
    path('curso/', include('Curso.urls')),  # novo path
    path('festivais/', include('festivais.urls')),  # novo path
    path('autenticacao/', include('autenticacao.urls')),
    path('meteo/', include('meteo.urls')),
    path('', include('portfolio.urls')),
    path('artigos/', include('artigos.urls')),

    ]

bandasNovas/models.py
from django.db import models
from django import forms    # formulários Django



class Banda(models.Model):
    nome = models.CharField(max_length=100)
    nacionalidade_da_banda = models.CharField(max_length=100)
    foto_da_banda = models.ImageField(upload_to='media/bandas/', null=True, blank=True)

    def __str__(self):
        return self.nome

class BandaForm(forms.ModelForm):
  class Meta:
    model = Banda
    fields = '__all__'











class Album(models.Model):
    titulo = models.CharField(max_length=100)
    ano_de_lancamento = models.IntegerField()
    banda = models.ForeignKey(Banda, on_delete=models.CASCADE)
    capa = models.ImageField(upload_to='media/bandas/', null=True, blank=True)
    def __str__(self):
        return self.titulo



class AlbumForm(forms.ModelForm):
  class Meta:
    model = Album
    fields = ['titulo','ano_de_lancamento','capa']







class Musica(models.Model):
    nome = models.CharField(max_length=100)
    duracao = models.CharField(max_length=10)
    link = models.URLField()
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

class MusicaForm(forms.ModelForm):
  class Meta:
    model = Musica
    fields = ['nome','duracao','link']

bandasNovas/views.py
from django.shortcuts import render
from .models import Banda, Album, Musica,BandaForm, AlbumForm, MusicaForm
from django.contrib.auth.decorators import login_required, user_passes_test



def edita_banda(user):
    return user.groups.filter(name = 'Bandas').exists()



from django.shortcuts import redirect

def index_view(request):
    context = {
        'bandas': Banda.objects.all().order_by('nome'),
        'is_editor' : edita_banda(request.user),
    }
    return render(request, "bandasNovas/index.html", context)




#Banda--------------------------------------------------------------------------------------------------------------------------------------------
def banda_view(request, banda_id):
    context = {
        'banda': Banda.objects.get(id=banda_id),
        'albums':Album.objects.filter(banda=Banda.objects.get(id=banda_id)),
        'is_editor' : edita_banda(request.user),

    }
    return render(request, "bandasNovas/banda.html", context)

@login_required
@user_passes_test(edita_banda)
def nova_banda_view(request):

    form = BandaForm(request.POST or None, request.FILES)  # request.FILES deve ser incluido se forem enviados ficheiros ou imagens
    if form.is_valid():
        form.save()
        return redirect('bandasNovas:bandas')

    context = {'form': form}
    return render(request, 'editar/nova_banda.html', context)


@login_required
@user_passes_test(edita_banda)
def edita_banda_view(request,banda_id):
    banda_certa = Banda.objects.get(id=banda_id)

    if request.POST:
        form = BandaForm(request.POST or None, request.FILES, instance=banda_certa)
        if form.is_valid():
            form.save()
            return redirect('bandasNovas:banda', banda_id=banda_id)
    else:
        form = BandaForm(instance=banda_certa)  # cria formulário com dados da instância autor

    context = {'form': form, 'banda':banda_certa}
    return render(request, 'editar/edita_banda.html', context)



def apaga_banda_view(request, banda_id):
    banda = Banda.objects.get(id=banda_id)
    banda.delete()
    return redirect('bandasNovas:bandas')
#Feito--------------------------------------------------------------------------------------------------------------------------------------------









#Album--------------------------------------------------------------------------------------------------------------------------------------------
def album_view(request, album_id):
    context = {
        'album': Album.objects.get(id=album_id),
        'musicas': Musica.objects.filter(album = Album.objects.get(id=album_id)),
        'is_editor' : edita_banda(request.user),
    }
    return render(request, "bandasNovas/album.html", context)






@login_required
@user_passes_test(edita_banda)
def novo_album_view(request, banda_id):
    banda_certa = Banda.objects.get(id = banda_id)
    form = AlbumForm(request.POST or None, request.FILES)

    if form.is_valid():
        album = form.save(commit=False)
        album.banda = banda_certa
        album.save()
        return redirect('bandasNovas:banda', banda_id=banda_id)

    context = {'form': form}
    return render(request, 'editar/novo_album.html', context)





@login_required
@user_passes_test(edita_banda)
def edita_album_view(request,album_id):
    album_certo = Album.objects.get(id=album_id)

    if request.POST:
        form = AlbumForm(request.POST or None, request.FILES, instance=album_certo)
        if form.is_valid():
            form.save()
            return redirect('bandasNovas:album', album_id=album_id)
    else:
        form = AlbumForm(instance=album_certo)  # cria formulário com dados da instância autor

    context = {'form': form, 'album':album_certo}
    return render(request, 'editar/edita_album.html', context)




def apaga_album_view(request, album_id):
    album = Album.objects.get(id=album_id)
    banda_id = album.banda.id
    album.delete()
    return redirect('bandasNovas:banda', banda_id=banda_id)
#Feito--------------------------------------------------------------------------------------------------------------------------------------------







#Musica--------------------------------------------------------------------------------------------------------------------------------------------

def musica_view(request, musica_id):
    context = {
        'musica': Musica.objects.get(id=musica_id),
        'is_editor' : edita_banda(request.user),
    }
    return render(request, "bandasNovas/musica.html", context)


@login_required
@user_passes_test(edita_banda)
def nova_musica_view(request, album_id):
    album_certo = Album.objects.get(id = album_id)
    form = MusicaForm(request.POST or None, request.FILES)

    if form.is_valid():
        musica = form.save(commit=False)
        musica.album = album_certo
        musica.save()
        return redirect('bandasNovas:album', album_id=album_id)

    context = {'form': form}
    return render(request, 'editar/nova_musica.html', context)

@login_required
@user_passes_test(edita_banda)
def edita_musica_view(request,musica_id):
    musica_certa = Musica.objects.get(id=musica_id)

    if request.POST:
        form = MusicaForm(request.POST or None, request.FILES, instance=musica_certa)
        if form.is_valid():
            form.save()
            return redirect('bandasNovas:musica', musica_id=musica_id)
    else:
        form = MusicaForm(instance=musica_certa)  # cria formulário com dados da instância autor

    context = {'form': form, 'musica':musica_certa}
    return render(request, 'editar/edita_musica.html', context)



def apaga_musica_view(request, musica_id):
    musica = Musica.objects.get(id=musica_id)
    album_id = musica.album.id
    musica.delete()
    return redirect('bandasNovas:album', album_id=album_id)
#Feito--------------------------------------------------------------------------------------------------------------------------------------------

bandasNovas/templates/bandasNovas/album.html
{% extends 'bandasNovas/layout.html' %}

{% block content %}
    <div style="background-color: #1a1a1a; padding: 70px; border-radius: 10px;">
            <h2 style="color: #ffffff;">{{ album }}</h2>

            <img src='{{ album.capa.url}}' width="300px">



        <p style="color: #ffffff;"><strong>Ano de Lançamento:</strong> {{ album.ano_de_lancamento }}</p>

        <p style="color: #ffffff;"><strong>Músicas:</strong></p>
         <div class="music-container">
            {% for musica in musicas %}

                    <a href="{% url 'bandasNovas:musica' musica.id %}">
                        <button class="spotify-green-button">{{ musica.nome }}</button>

                    </a>

            {% endfor %}

        </div>

        {% if request.user.is_authenticated and is_editor %}
            <a href="{% url 'bandasNovas:edita_album' album.id %}">
                <input type="submit" value="Editar informação do Album">
            </a>
            <a href="{% url 'bandasNovas:cria_musica' album.id %}">
                <input type="submit" value="Criar nova musica do Album">
            </a>
            <a href="{% url 'bandasNovas:apaga_album' album.id %}">
                <button>Apagar album e suas musicas</button>
            </a>
        {% endif %}
    </div>


    <style>

    </style>
{% endblock %}

bandasNovas/templates/bandasNovas/banda.html
{% extends 'bandasNovas/layout.html' %}

{% block content %}
    <div style="background-color: #1a1a1a; padding: 20px; border-radius: 10px;">
        <h2 style="color: #ffffff;">{{ banda }}</h2>
        <p style="color: #ffffff;"><strong>Nacionalidade:</strong> {{ banda.nacionalidade_da_banda }}</p>

        <p style="color: #ffffff;"><strong>Álbuns:</strong></p>
        <ul style="list-style-type: none; padding: 0;">
            <div class="album-container">
                {% for album in albums %}
                    <div class="album">
                        <a href="{% url 'bandasNovas:album' album.id %}">
                            <img src="{{ album.capa.url }}" alt="{{ album.titulo }}">
                        </a>
                        <span>{{ album.titulo }}</span>
                    </div>
                {% endfor %}
            </div>
        </ul>

        {% if request.user.is_authenticated and is_editor %}
            <a href="{% url 'bandasNovas:edita_banda' banda.id %}">
                <input type="submit" value="Editar informação da Banda">
            </a>
        {% endif %}

        {% if request.user.is_authenticated and is_editor %}
            <a href="{% url 'bandasNovas:cria_album' banda.id %}">
                <input type="submit" value="Criar novo album da Banda">
            </a>
        {% endif %}

        {% if request.user.is_authenticated and is_editor %}
            <a href="{% url 'bandasNovas:apaga_banda' banda.id %}">
                <button>Apagar Banda e os seus albuns e musicas</button>
            </a>
        {% endif %}
    </div>

    <style>

    </style>
{% endblock %}

bandasNovas/templates/bandasNovas/index.html
{% extends 'bandasNovas/layout.html' %}

{% block content %}

    <div style="position: relative; background-color: #1a1a1a; padding: 10px; border-radius: 10px">

        {% if request.user.is_authenticated and is_editor %}
            <a href="{% url 'bandasNovas:cria_banda' %}" class="create-band-button">
                <input type="submit" value="Criar nova Banda">
            </a>
        {% endif %}

        <h2 style="color: #ffffff;">Lista de Bandas</h2>

        <p style="color: #ffffff;"><strong>Total de Bandas:</strong> {{ bandas|length }}</p>

        <ul style="list-style-type: none; padding: 0;">
            <div class="artists-container">
                {% for banda in bandas %}
                    <div class="artist">
                        <a href="{% url 'bandasNovas:banda' banda.id %}">
                            <img src="{{ banda.foto_da_banda.url }}" alt="{{ banda.nome }}">
                        </a>
                        <span>{{ banda.nome }}</span>
                    </div>
                {% endfor %}
            </div>
        </ul>
    </div>

{% endblock %}

bandasNovas/templates/bandasNovas/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bandas/estilos.css' %}">
    <title>Bandas</title>
</head>
<body>
    <div class="container">
        <div class="sidebar">
            <h1>Bandas</h1>
            <a href="{% url 'bandasNovas:bandas' %}"><i class="material-icons">home</i>Página Inicial</a>
            <a href="{% url 'curso:cursos' %}"><i class="material-icons">school</i>Curso</a>
            <a href="{% url 'portfolio:landing' %}"><i class="material-icons">folder</i>Portfolio</a>
            <a href="#"><i class="material-icons">article</i>Artigos</a>
            <a href="{% url 'meteo:tempo_lisboa' %}"><i class="material-icons">wb_sunny</i>Meteorologia</a>
            {% if request.user.is_authenticated %}
                <div class="username">
                    <i class="material-icons">person</i>
                    <p>{{ request.user.username }}</p>
                </div>
                <a href="{% url 'autenticacao:logout' %}"><button><i class="material-icons">logout</i>Logout</button></a>
            {% else %}
                <a href="{% url 'autenticacao:login' %}"><button><i class="material-icons">login</i>Login</button></a>
            {% endif %}
        </div>
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </div>
    <footer>
        <p>&copy; {% now "Y" %} Direitos reservados ao autor.</p>
    </footer>
</body>
</html>

bandasNovas/templates/bandasNovas/musica.html
{% extends 'bandasNovas/layout.html' %}

{% block content %}
    <div style="background-color: #1a1a1a; padding: 20px; border-radius: 10px;">
        <h3 style="color: #ffffff;">{{ musica }}</h3>

        <p style="color: #ffffff;"><strong>Duração:</strong> {{ musica.duracao }}</p>
        <p style="color: #ffffff;"><strong>Link da música:</strong> <a href="{{ musica.link }}" style="color: #ffffff; text-decoration: none;">{{ musica.link }}</a></p>
        {% if request.user.is_authenticated and is_editor %}
            <a href="{% url 'bandasNovas:edita_musica' musica.id %}">
                <input type="submit" value="Editar informação da Musica">
            </a>
        {% endif %}
    </div>

    {% if request.user.is_authenticated and is_editor %}
        <a href="{% url 'bandasNovas:apaga_musica' musica.id %}">
            <input type="submit" value="Apagar musica">
        </a>
    {% endif %}

    <style>
    @import url(estilo.css)
    </style>
{% endblock %}